# Generated by Django 3.2.5 on 2021-12-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumniApp', '0002_post_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='batchyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='branch',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='linkedinId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='rollno',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
