# Generated by Django 3.2.5 on 2021-12-25 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AlumniApp', '0003_auto_20211224_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=30, null=True)),
                ('role', models.CharField(max_length=50, null=True)),
                ('eligibility', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=600, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('applylink', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
